pipeline {
    agent any
    
    environment {
        region = 'us-east-2'
        bucket_name = 'staticwebsitebucket123'
    }

    stages {
        stage('git files') {
            steps {
                git branch: 'main', url: 'https://github.com/narendrapb/challenges.git'
            }
        }
        
        stage('aws login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws', usernameVariable: 'AccessKey', passwordVariable: 'SecretKey')]) {
                    script {
                        sh """
                        aws configure set region us-east-2 --profile default
                        aws configure set aws_access_key_id ${AccessKey} --profile default
                        aws configure set aws_secret_access_key ${SecretKey} --profile default
                        """
                    }
                }
            }
        }
        
        stage('s3 Upload') {
            steps {
                script {
                    echo "Workspace directory: ${env.WORKSPACE}"
                    sh 'pwd'
                    sh 'ls'
                    dir('challenge1') {
                        sh 'ls'
                    }
                    sh "aws s3 cp ${env.WORKSPACE}/challenge1 s3://${bucket_name}/ --recursive"
                }
            }
        }
    }
}
